version: '3.7'

services:

  zookeeper:
    platform: linux/amd64
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  
  kafka:
    platform: linux/amd64
    image: confluentinc/cp-kafka:7.3.0
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  
  
  connect:
    platform: linux/amd64
    image: debezium/connect:2.2
    ports:
      - 8083:8083
    depends_on:
      - kafka
    links:
      - kafka
      - zookeeper
    
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

networks:
  default:
    name: cdc-network
    external: true